import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apurva's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" className="dark">
      {/* <head>
        <title>Apurva&aposs Portfolio</title>
        <meta name='description' content='Description' />
      </head> */}
        <body className={inter.className}>
            <div className="relative w-full flex items-center justify-center">
                <Navbar />
            </div>
            {children}
        </body>
    </html>
  );
}
